"""Typed records used across the autonomous research agent."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any


JsonDict = dict[str, Any]


def utc_now_iso() -> str:
    """Return an ISO timestamp in UTC."""
    return datetime.now(timezone.utc).isoformat()


@dataclass(frozen=True)
class Hypothesis:
    """A causal, testable hypothesis generated by the LLM."""

    hypothesis: str
    filters: JsonDict
    reasoning: str
    expected_behavior: str
    source: str = "opencode"

    def to_dict(self) -> JsonDict:
        """Serialize to a JSON-friendly dict."""
        return asdict(self)


@dataclass
class ResultSummary:
    """Stable subset of conditional_analysis.FilterResult."""

    n_trades: int
    win_rate: float
    sharpe: float
    p_value: float
    verdict: str
    mean_pnl_net_pips: float
    max_drawdown_pips: float
    filter_hash: str

    @classmethod
    def from_filter_result(cls, result: Any) -> "ResultSummary":
        """Build from the existing conditional analysis result object."""
        return cls(
            n_trades=int(result.n_trades),
            win_rate=float(result.win_rate),
            sharpe=float(result.sharpe),
            p_value=float(result.p_value_vs_coinflip),
            verdict=str(result.verdict),
            mean_pnl_net_pips=float(result.mean_pnl_net_pips),
            max_drawdown_pips=float(result.max_drawdown_pips),
            filter_hash=str(result.filter_hash),
        )

    def to_dict(self) -> JsonDict:
        """Serialize to a JSON-friendly dict."""
        return asdict(self)


@dataclass
class EvaluationRecord:
    """Full lifecycle record for one tested hypothesis."""

    hypothesis: Hypothesis
    filter_hash: str
    research: ResultSummary | None = None
    holdout: ResultSummary | None = None
    status: str = "created"
    verdict: str = "PENDING"
    insight: str = ""
    created_at: str = field(default_factory=utc_now_iso)

    def to_dict(self) -> JsonDict:
        """Serialize to a JSON-friendly dict."""
        return {
            "hypothesis": self.hypothesis.to_dict(),
            "filter_hash": self.filter_hash,
            "research": self.research.to_dict() if self.research else None,
            "holdout": self.holdout.to_dict() if self.holdout else None,
            "status": self.status,
            "verdict": self.verdict,
            "insight": self.insight,
            "created_at": self.created_at,
        }
